version: '3.8'
services:
  frontend:
    platform: linux/amd64
    build:
      context: ./rtagents/RTAgent/frontend
      dockerfile: Dockerfile
      
    env_file:
      - ./rtagents/RTAgent/frontend/.env
    ports:
      - "8080:8080"
    
  # Be sure to run the devtunnel if developing locally
  # and to update the root .env file with the tunnel URL
  backend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./rtagents/RTAgent/backend/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8010:8010"