version: '3.8'
services:
  frontend:
    platform: linux/amd64
    build:
      context: ./rtagents/RTInsuranceAgent/frontend
      # context: ./usecases/browser_RTMedAgent/frontend
      dockerfile: Dockerfile
      
    env_file:
      - ./rtagents/RTInsuranceAgent/frontend/.env
    ports:
      - "5173:5173"
    

  # Be sure to run the devtunnel if developing locally
  # and to update the root .env file with the tunnel URL
  backend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./rtagents/RTInsuranceAgent/backend/Dockerfile
      # dockerfile: ./usecases/browser_RTMedAgent/backend/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8010:8010"