name: audioagent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  # Note: All Python dependencies are now managed through pyproject.toml
  # Use 'uv sync' or 'uv sync --dev' to install dependencies
