modalities:
  - text
  - audio
voice: "ballad"
input_audio_format: "pcm16"
output_audio_format: "pcm16"
input_audio_transcription:
  model: "whisper-1"
# OR you can set to null:
# input_audio_transcription: null
turn_detection:
  type: "server_vad"  # or "none"
  threshold: 0.5
  prefix_padding_ms: 300
  silence_duration_ms: 200
  create_response: true
tools: []  # Empty list, or define your tools here
tool_choice: "auto"
temperature: 1.0  # or 0.8 for more stable responses
max_response_output_tokens: 4096  # or "inf"
