name: Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Install azd
        uses: Azure/setup-azd@v0.1.0
      
      - name: Deploy with azd
        env:
          AZURE_ENV_NAME: production
          AZURE_LOCATION: eastus
          ACS_SOURCE_PHONE_NUMBER: ${{ secrets.ACS_PHONE_NUMBER }}
          # CI is automatically set by GitHub Actions
        run: |
          azd auth login --client-id ${{ secrets.AZURE_CLIENT_ID }} \
            --client-secret ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant-id ${{ secrets.AZURE_TENANT_ID }}
          
          azd env new $AZURE_ENV_NAME
          azd up --no-prompt