name: 🎯 Complete Deployment with AZD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      action:
        description: 'Action to perform'
        required: true
        default: 'up'
        type: choice
        options:
          - provision  # Infrastructure only
          - deploy     # Application only
          - up         # Both infrastructure and application
          - down       # Destroy everything

jobs:
  # ============================================================================
  # COMPLETE DEPLOYMENT WITH AZD
  # ============================================================================
  complete-deployment:
    name: 🚀 Deploy with Azure Developer CLI
    uses: ./.github/workflows/templates/deploy-azd.yml
    with:
      environment: ${{ inputs.environment }}
      action: ${{ inputs.action }}
    secrets: inherit

  # ============================================================================
  # DEPLOYMENT SUMMARY
  # ============================================================================
  deployment-summary:
    name: 📋 Deployment Summary
    runs-on: ubuntu-latest
    needs: [complete-deployment]
    if: always()
    
    steps:
      - name: 📋 Generate Summary
        run: |
          echo "## 🎯 Azure Developer CLI Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Status | Environment | Action |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|-------------|---------|" >> $GITHUB_STEP_SUMMARY
          
          DEPLOYMENT_STATUS="${{ needs.complete-deployment.result }}"
          if [ "$DEPLOYMENT_STATUS" = "success" ]; then
            echo "| 🚀 Deployment | ✅ Success | \`${{ inputs.environment }}\` | \`${{ inputs.action }}\` |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 🚀 Deployment | ❌ Failed | \`${{ inputs.environment }}\` | \`${{ inputs.action }}\` |" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ inputs.action }}" != "down" ] && [ "$DEPLOYMENT_STATUS" = "success" ]; then
            echo "### 🔗 Application URLs" >> $GITHUB_STEP_SUMMARY
            
            if [ -n "${{ needs.complete-deployment.outputs.frontend_url }}" ]; then
              echo "- 🌐 **Frontend**: [${{ needs.complete-deployment.outputs.frontend_url }}](${{ needs.complete-deployment.outputs.frontend_url }})" >> $GITHUB_STEP_SUMMARY
            fi
            
            if [ -n "${{ needs.complete-deployment.outputs.backend_url }}" ]; then
              echo "- 🔧 **Backend**: [${{ needs.complete-deployment.outputs.backend_url }}](${{ needs.complete-deployment.outputs.backend_url }})" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📊 Resource Group" >> $GITHUB_STEP_SUMMARY
            echo "- 📦 **Resource Group**: \`${{ needs.complete-deployment.outputs.resource_group }}\`" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🛠️ Azure Developer CLI" >> $GITHUB_STEP_SUMMARY
          echo "This deployment was managed using Azure Developer CLI (azd) which provides:" >> $GITHUB_STEP_SUMMARY
          echo "- 🏗️ **Infrastructure**: Terraform-based provisioning" >> $GITHUB_STEP_SUMMARY
          echo "- 📦 **Application**: Container-based deployment" >> $GITHUB_STEP_SUMMARY
          echo "- 🔄 **Lifecycle**: Complete deployment lifecycle management" >> $GITHUB_STEP_SUMMARY
